export const JOB_OUTREACH_SPREADSHEET_NAME = "Job Outreach Pipeline";

export const jobOutreachTabs = [
  {
    name: "Leads",
    columns: [
      "Lead ID",
      "Date Added",
      "Source",
      "First Name",
      "Last Name",
      "Full Name",
      "Email",
      "LinkedIn URL",
      "Job Title",
      "Company",
      "Company Website",
      "Company Industry",
      "Company Size",
      "Location",
      "Hiring Signal",
      "Tech Signal",
      "Personalization Angle",
      "Lead Score",
      "Lead Status",
      "Notes",
    ],
  },
  {
    name: "Outreach Queue",
    columns: [
      "Queue ID",
      "Lead ID",
      "Priority",
      "Email Type",
      "Subject Line",
      "Email Body",
      "Approval Status",
      "Send Mode",
      "Scheduled Send Date",
      "Sent Status",
      "Error Message",
    ],
  },
  {
    name: "Email Activity",
    columns: [
      "Activity ID",
      "Lead ID",
      "Email",
      "Email Type",
      "Subject",
      "Sent Date",
      "Gmail Message ID",
      "Status",
      "Follow-up Due Date",
      "Notes",
    ],
  },
  {
    name: "Replies",
    columns: [
      "Reply ID",
      "Lead ID",
      "From Email",
      "Reply Date",
      "Reply Snippet",
      "AI Classification",
      "Sentiment",
      "Next Action",
      "Drafted Response",
      "Human Reviewed",
    ],
  },
  {
    name: "Follow Ups",
    columns: [
      "Follow-up ID",
      "Lead ID",
      "Follow-up Number",
      "Due Date",
      "Status",
      "Reason",
      "Email Body",
      "Approval Status",
    ],
  },
  {
    name: "Interviews",
    columns: [
      "Interview ID",
      "Lead ID",
      "Company",
      "Contact Name",
      "Calendly Event ID",
      "Interview Date",
      "Interview Time",
      "Meeting Link",
      "Status",
      "Notes",
    ],
  },
  {
    name: "Suppression List",
    columns: ["Email", "Name", "Company", "Reason", "Date Added"],
  },
  {
    name: "Templates",
    columns: ["Template ID", "Template Name", "Subject Pattern", "Email Body Pattern", "Use Case", "Active"],
  },
  {
    name: "Settings",
    columns: ["Setting", "Value"],
  },
  {
    name: "Daily Metrics",
    columns: [
      "Date",
      "Leads Sourced",
      "Qualified Leads",
      "Drafts Generated",
      "Emails Sent",
      "Replies Received",
      "Positive Replies",
      "Interviews Booked",
      "Bounce Count",
      "Opt-outs",
      "Best Performing Segment",
      "Notes",
    ],
  },
] as const;

export const jobOutreachSettings = [
  ["Daily Lead Source Limit", "50"],
  ["Daily Email Send Limit", "25"],
  ["Minimum Lead Score to Draft", "70"],
  ["Minimum Lead Score to Auto Send", "85"],
  ["Follow-up 1 Delay", "3 days"],
  ["Follow-up 2 Delay", "7 days"],
  ["Final Follow-up Delay", "14 days"],
  ["Sending Mode", "Draft Only"],
  ["Auto Send", "Disabled"],
  ["Calendly Link", "ADD_CALENDLY_LINK"],
  ["Sender Name", "Princewill Ejiogu"],
  ["Sender Email", "ADD_APPROVED_SENDER_EMAIL"],
] as const;

export const jobOutreachConfig = {
  projectName: "Interview Pipeline Mission Control",
  mode: "draft_only",
  dailyLeadLimit: 50,
  dailySendLimit: 25,
  minimumScoreToDraft: 70,
  minimumScoreToAutoSend: 85,
  followUpDelays: {
    first: 3,
    second: 7,
    final: 14,
  },
  sender: {
    name: "Princewill Ejiogu",
    email: "ADD_APPROVED_SENDER_EMAIL",
  },
  calendly: {
    link: "ADD_CALENDLY_LINK",
  },
  apollo: {
    enabled: true,
    searchLimitPerRun: 50,
    termsAndRateLimitsRequired: true,
  },
  googleSheets: {
    spreadsheetName: JOB_OUTREACH_SPREADSHEET_NAME,
    spreadsheetId: "ADD_SPREADSHEET_ID_AFTER_CREATION",
    tabs: jobOutreachTabs.map((tab) => tab.name),
  },
  safety: {
    requireApprovalBeforeSend: true,
    respectSuppressionList: true,
    stopFollowUpsAfterReply: true,
    stopFollowUpsAfterOptOut: true,
    logEveryActivity: true,
  },
} as const;
